/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSessionsRouteImport } from './routes/app.sessions'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppCaptureRouteImport } from './routes/app.capture'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppDevicesIpRouteImport } from './routes/app.devices.$ip'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesIpRoute = AppDevicesIpRouteImport.update({
  id: '/$ip',
  path: '/$ip',
  getParentRoute: () => AppDevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/devices': typeof AppDevicesRouteWithChildren
  '/app/graph': typeof AppGraphRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/': typeof AppIndexRoute
  '/app/devices/$ip': typeof AppDevicesIpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/devices': typeof AppDevicesRouteWithChildren
  '/app/graph': typeof AppGraphRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app': typeof AppIndexRoute
  '/app/devices/$ip': typeof AppDevicesIpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/capture': typeof AppCaptureRoute
  '/app/devices': typeof AppDevicesRouteWithChildren
  '/app/graph': typeof AppGraphRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/': typeof AppIndexRoute
  '/app/devices/$ip': typeof AppDevicesIpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/capture'
    | '/app/devices'
    | '/app/graph'
    | '/app/overview'
    | '/app/sessions'
    | '/app/'
    | '/app/devices/$ip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/alerts'
    | '/app/capture'
    | '/app/devices'
    | '/app/graph'
    | '/app/overview'
    | '/app/sessions'
    | '/app'
    | '/app/devices/$ip'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/capture'
    | '/app/devices'
    | '/app/graph'
    | '/app/overview'
    | '/app/sessions'
    | '/app/'
    | '/app/devices/$ip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/capture': {
      id: '/app/capture'
      path: '/capture'
      fullPath: '/app/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices/$ip': {
      id: '/app/devices/$ip'
      path: '/$ip'
      fullPath: '/app/devices/$ip'
      preLoaderRoute: typeof AppDevicesIpRouteImport
      parentRoute: typeof AppDevicesRoute
    }
  }
}

interface AppDevicesRouteChildren {
  AppDevicesIpRoute: typeof AppDevicesIpRoute
}

const AppDevicesRouteChildren: AppDevicesRouteChildren = {
  AppDevicesIpRoute: AppDevicesIpRoute,
}

const AppDevicesRouteWithChildren = AppDevicesRoute._addFileChildren(
  AppDevicesRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCaptureRoute: typeof AppCaptureRoute
  AppDevicesRoute: typeof AppDevicesRouteWithChildren
  AppGraphRoute: typeof AppGraphRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCaptureRoute: AppCaptureRoute,
  AppDevicesRoute: AppDevicesRouteWithChildren,
  AppGraphRoute: AppGraphRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
